services:
  - type: web
    name: smart-expiry-tracker
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput --clear"
    startCommand: "gunicorn expirytracker.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: expirytracker.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: smart-expiry-db
          property: connectionString

databases:
  - name: smart-expiry-db
    databaseName: smart_expiry_tracker
    user: smart_expiry_user
